config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/owner", to: "pages#owner"

  resources :users, only: [:show]
  resources :locations, only: [:create, :update]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :businesses do
    resources :products
  end

  post "/businesses", to: "business#create", as: "post_business"

  get "/products", to: "products#list_all"
  get "/products/:id", to: "products#show_selected", as: "product_show"

  resources :itineraries, only: [:new, :update]
  get "/itineraries/:product_id/generate", to: "itineraries#create", as: "create_itinerary"
  get "/my_itineraries", to: "itineraries#index", as: "my_itinerary"
  get "/my_itineraries/:id", to: "itineraries#show", as: "my_itineraries"
  get "/my_itineraries/:id/add_products", to: "itineraries#add_products", as: "add_products"
  patch "/my_itineraries/:id/update/:element", to: "itineraries#update_element", as: "update_element"
  post "my_itineraries/product/:product_id/:itinerary_id/add", to: "itineraries#add_product_to_itinerary", as: "add_product_to_itinerary"
  delete "my_itineraries/product/:product_id/:itinerary_id/remove", to: "itineraries#remove_product_of_itinerary", as: "remove_product_of_itinerary"
  get "my_itineraries/:itinerary_id/get_itinerary", to: "itineraries#itinerary_route", as: "itinerary_route"
  get "my_itineraries/:id/add_stop/new", to: "stops#new", as: "itinerary_stops"
  post "my_itineraries/:id/add_stop/new", to: "stops#create", as: "itinerary_stops_create"
  patch "my_itineraries/:id/completed", to: "itineraries#mark_itinerary_as_completed", as: "mark_as_complete"
  get "history", to:"itineraries#history_itineraries", as: "history_itineraries"
  patch ":id/undo_and_set_current", to: "itineraries#undo_and_set_as_current", as: "undo_and_set_as_current"
  patch ":id/set_as_current", to: "itineraries#set_as_current", as: "set_as_current"
  patch ":id/remove_as_current", to: "itineraries#remove_as_current", as: "remove_as_current"
end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  has_many :saved_itineraries
  has_many :product_itineraries
  has_many :products, through: :product_itineraries
  has_many :stops

  def has?(element)
    products = self.products
    result = products.select { |product| product == element }
    return result.length == 1
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController

  skip_before_action :verify_authenticity_token, only: [:add_product_to_itinerary, :remove_product_of_itinerary]
  def new
    seek = params[:filters].nil? ? "" : params[:filters][:seek]
    address = params[:filters].nil? ? "" : params[:filters][:address]
    query = search_engine(seek, address)
    @products = query[0]
    @counter = query[1]
  end

  def create
    @product = Product.find(params[:product_id])
    @itinerary = Itinerary.new(new_itinerary_params)
    if @itinerary.save
      saved_itinerary = SavedItinerary.new(itinerary: @itinerary, user: current_user, date: Date.today)
      if saved_itinerary.save
        product_itinerary = ProductItinerary.new(itinerary: @itinerary, product: @product)
        redirect_to add_products_path(@itinerary) if product_itinerary.save
      else
        redirect_to root_path
      end
    end
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    @stops = @itinerary.stops
  end

  def index
    @saved_itineraries = current_user.saved_itineraries
  end

  def add_more_products
    @itinerary = Itinerary.find(params[:id])
    @display_adding_products_logic = ((controller_name == "itineraries" && action_name == "add_products") || controller_name == "products" && action_name=="list_all" )
    @display_navbar_logic = ((user_signed_in? && (controller_name == "pages" || (controller_name == "itineraries" && (action_name == "new" || action_name == "add_products") ))) || controller_name == "products")
  end

  def update
    @itinerary = Itinerary.find(params[:id])
    @saved_itinerary = SavedItinerary.find(params[:itinerary][:saved_itinerary][:saved_itinerary_id])
    @itinerary.update(new_itinerary_params)
    respond_to do |format|
      format.html { redirect_to my_itineraries_path }
      format.text { render partial: "itineraries/itinerary_info", locals: {saved_itinerary: @saved_itinerary}, formats: [:html] }
    end
  end

  def update_element
    element = params[:element]
    if element == "name"
      @itinerary = Itinerary.find(params[:id])
      @itinerary.update(new_itinerary_params)
      respond_to do |format|
        format.html { redirect_to my_itineraries_path(@itinerary) }
        format.text { render partial: "itineraries/itinerary_show_name", locals: {itinerary: @itinerary}, formats: [:html] }
      end
    elsif element == "date"
      @saved_itinerary = SavedItinerary.find(params[:id])
      @saved_itinerary.update(saved_itinerary_params)
      respond_to do |format|
        format.html { redirect_to my_itineraries_path(@itinerary) }
        format.text { render partial: "itineraries/itinerary_show_date", locals: {saved_itinerary: @saved_itinerary}, formats: [:html] }
      end
    end
  end

  def add_products
    seek = params[:filters].nil? ? "" : params[:filters][:seek]
    address = params[:filters].nil? ? "" : params[:filters][:address]
    @itinerary = Itinerary.find(params[:id])
    query = search_engine(seek, address)
    @products = query[0]
    @counter = query[1]
  end

  def add_product_to_itinerary
    @product = Product.find(params[:product_id])
    @itinerary = Itinerary.find(params[:itinerary_id])
    ProductItinerary.create(itinerary: @itinerary, product: @product)
    respond_to do |format|
      format.html
      format.text { render partial: "itineraries/itinerary_add_product_card", locals: {itinerary: @itinerary, product: @product}, formats: [:html] }
    end
  end

  def mark_itinerary_as_completed
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(new_itinerary_params)
    @itinerary.update(current: false)
    redirect_to history_itineraries_path
  end

  def history_itineraries
    @itineraries = current_user.itineraries
  end

  def remove_product_of_itinerary
    @product = Product.find(params[:product_id])
    @itinerary = Itinerary.find(params[:itinerary_id])
    ProductItinerary.where(product: @product, itinerary: @itinerary).first.destroy
    respond_to do |format|
      format.html {redirect_to add_products_path(@itinerary)}
      format.text { render partial: "itineraries/itinerary_add_product_card", locals: {itinerary: @itinerary, product: @product}, formats: [:html] }
    end
  end

  def set_as_current
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(new_itinerary_params)
    redirect_to root_path
  end

  def remove_as_current
    @itinerary = Itinerary.find(params[:id])
    @itinerary.update(new_itinerary_params)
    redirect_to my_itineraries_path(@itinerary)
  end

  def undo_and_set_as_current
    @itinerary = Itinerary.find(params[:id])
    current_user.itineraries.each do |itinerary|
      itinerary.update(current: false) if itinerary.current
    end
    @itinerary.update(new_itinerary_params)
    redirect_to root_path
  end

  private

  # The seach engine method is using pgsearch gem. To edit the query setting go to the Product Model.
  def search_engine(seek, address)
    products = []
    if seek != "" && address != ""
      Product.search_by_product(seek).each do |product|
        Business.near(address, 20).each do |business|
          products << product if product.business == business
        end
      end
    elsif address != ""
      Business.near(address, 20).each do |business|
        business.products.each do |product|
          products << product unless product.nil?
        end
      end
    elsif seek != ""
      products = Product.search_by_product(seek)
    end
    return [products, products.count || 0] # Polimorfism!!!
  end

  def new_itinerary_params
    params.require(:itinerary).permit(:name, :status, :current)
  end

  def saved_itinerary_params
    params.require(:saved_itinerary).permit(:date)
  end
end

app/views/itineraries/_itinerary_add_product_card.html.erb
<div data-controller="itinerary-add-products">
      <div class="card m-3" style="width: 20rem;" data-itinerary-add-products-target="productCard" id="<%= product.id %>" >
        <input type="hidden" data-itinerary-add-products-target="itineraryId" value="<%= itinerary.id %>">
        <% if product.photos[0]!=nil %>
          <%= cl_image_tag product.photos[0].key, height: 300, width: 300, crop: :fill, class:"card-img-top bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
        <%else%>
          <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="" style="height: 300px; width: 319px;">
        <% end %>
        <div class="card-body">
          <h4 class="card-text"><%= product.brand %>, <%= product.name %></h4>
          <div class="d-flex flex-column">
            <div class="d-flex flex-row justify-content-between align-items-center" style="margin-bottom:-1px;">
              <h5><span><i class="fa-solid fa-tag"></i></span> $<%= "%.2f" % product.price.round %></h5>
              <% if product.availability  %>
                <span class="badge bg-success badge-pill badge-success">Available</span>
              <% else %>
                <span class="badge bg-warning badge-pill badge-success">Out of stock</span>
              <% end %>
            </div>
            <p style="margin-bottom:-2px;"><i class="fa-solid fa-compass-drafting"></i> Distance: <%=  "%.2f" % Geocoder::Calculations.distance_between([current_user.location.latitude, current_user.location.longitude], [product.latitude, product.longitude])%>km</p>
            <p style="margin-bottom:-2px;"><i class="fa-solid fa-clock"></i> <%= product.business.opening_time.strftime("%H:%M")%> - <%= product.business.closing_time.strftime("%H:%M")%><p>
            <div style="margin-top: 5px; margin-bottom: 10px">
              <%= link_to "See up close!", product_show_path(product), class: "blue-btn"%>
            </div>
              <% if itinerary.has?(product)  %>
                <%= simple_form_for itinerary, method: "DELETE",data: {action: "submit->itinerary-add-products#deleteProduct", itinerary_add_products_target:"removeForm"} do |f| %>
                <%= f.submit "Delete product", class:"btn btn-danger", style: "color: white;" %>
                <% end %>
              <% else %>
                <%= simple_form_for itinerary, method: "POST",data: {action: "submit->itinerary-add-products#addProduct", itinerary_add_products_target:"addForm"} do |f| %>
                <%= f.submit "Add product+", class:"btn btn-dark", style:"background-color: #2997D8; border: #2997D8;" %>
                <% end %>
              <% end %>
            <div>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/itineraries/_itinerary_info.html.erb
<div class="card m-3" data-itineraries-index-target="info">
  <h5 class="card-header" data-itineraries-index-target="name"><strong><%= saved_itinerary.itinerary.name %></strong> &nbsp<span data-action="click->itineraries-index#displayForm"><i class="fa-solid fa-pencil"></i></span></h5>
  <%= simple_form_for saved_itinerary.itinerary, html: {class: "d-flex flex-row card-header align-content-center justify-content-between d-none", data: { itineraries_index_target: "form", action: "submit->itineraries-index#update"}} do |f| %>
    <%= f.input :name, label: false %>
    <%=  f.simple_fields_for :saved_itinerary do |i| %>
             <%= i.input :saved_itinerary_id, as: :hidden, input_html: {value: saved_itinerary.id} %>
          <% end %>
    <%= f.submit "Change name", class: "btn btn-dark h-50" %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title">This itinerary is scheduled to be used at <%= saved_itinerary.date %></h5>
    <p class="card-text">Your itinerary includes <%= pluralize(saved_itinerary.itinerary.products.count, "product") %></p>
    <%= link_to "See datails", my_itineraries_path(saved_itinerary.itinerary), class: "btn btn-dark" %>
  </div>
</div>

app/views/itineraries/_itinerary_show_date.html.erb
<span data-itinerary-show-target="date"><%= saved_itinerary.date %></span>

app/views/itineraries/_itinerary_show_name.html.erb
<h1 data-itinerary-show-target="name"><%= itinerary.name %>&nbsp<span style="font-size:20px" data-action="click->itinerary-show#displayNewNameForm"><i class="fa-solid fa-pencil"></i></span></h1>

app/views/itineraries/_new_search_engine_phone.html.erb
  <div style="" class="blue" id="sign-in-search-engine">
      <%= simple_form_for :filters, url: new_itinerary_path, method: :get do |f| %>
        <%= f.input :seek, placeholder: 'Categories, product name..', label: false,  class:"seek-search" %>
        <div class="nav-search" style="border-radius: 15px" >
          <%= f.input :address, label: false, input_html: {data: {address_autocomplete_target: "address"}, class: "mapboxgl-ctrl-geocoder--input d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
          <%= button_tag type: 'submit', class:"signed-in-search-glass-container btn" do %>
            <i class="fa-solid signed-in-search-glass fa-magnifying-glass"></i>
          <% end %>
        </div>
      <% end %>
    </div>

app/views/itineraries/_search_engine_phone.html.erb
  <div style="" class="blue" id="sign-in-search-engine">
      <%= simple_form_for :filters, url: add_products_path(itinerary), method: :get do |f| %>
        <%= f.input :seek, placeholder: 'Categories, product name..', label: false,  class:"seek-search" %>
        <div class="nav-search" style="border-radius: 15px" >
          <%= f.input :address, label: false, input_html: {data: {address_autocomplete_target: "address"}, class: "mapboxgl-ctrl-geocoder--input d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
          <%= button_tag type: 'submit', class:"signed-in-search-glass-container btn" do %>
            <i class="fa-solid signed-in-search-glass fa-magnifying-glass"></i>
          <% end %>
        </div>
      <% end %>
    </div>

app/views/itineraries/add_products.html.erb
<%= render "itineraries/search_engine_phone", itinerary: @itinerary %>
<div class="container m-2 p-3 d-flex flex-column" data-controller="itinerary-add-products">
  <div class="d-flex flex-row m-4 justify-content-between align-items-center">
    <h1><%= pluralize(@counter, "Result") %></h1>
    <% if @counter > 0 %>
      <%= link_to "Review #{@itinerary.name}", my_itineraries_path(@itinerary), class: "btn btn-primary ms-2 mb-4", style: "background-color:#2997D8 ; border-color:#2997D8 ;" %>
    <% end %>
  </div>
  <br>
  <div class="d-flex flex-wrap flex-row m-1">
  <% if @counter > 0 %>
    <% @products.each do |product| %>
      <%= render "itineraries/itinerary_add_product_card", itinerary: @itinerary, product: product %>
    <% end %>
  <% else %>
  <div class="container d-flex justify-content-center" style="height: 50vh">
    <div class="align-self-center d-flex flex-column align-items-center justify-content-center">
      <h2><i class="fa-solid fa-hand-point-up"></i></h2>
    <div class= "d-flex flex-row align-items-center">
      <h3 class="mb-4" style="text-align:center">Search for more products above or</h3>
      <%= link_to "Review #{@itinerary.name}", my_itineraries_path(@itinerary), class: "btn btn-primary ms-2 mb-4", style: "background-color:#2997D8 ; border-color:#2997D8 ;" %>
    </div>
  </div>
</div>
  <% end %>
  </div>
</div>

app/views/itineraries/history_itineraries.html.erb
<div class="container m-2 p-3 card border" style='height:70vh;'>
  <h1>Your previous itineraries</h1>
  <% @itineraries.each do |itinerary| %>
  <% if itinerary.status %>
  <div data-controller = "itineraries-index">
   <div class="card m-3" data-itineraries-index-target="info">
      <h5 class="card-header" data-itineraries-index-target="name"><strong><%= itinerary.name %></strong> </h5>
      <div class="card-body">
        <p class="card-text">Your itinerary included <%= pluralize(itinerary.products.count, "product") %></p>
      </div>
    </div>
  </div>
  <% end %>
<% end %>
</div>

app/views/itineraries/new.html.erb
<%= render "itineraries/new_search_engine_phone" %>
<div class="banner d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/135620/pexels-photo-135620.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
  <div id="banner-content" class="container">
    <h1>Products we've found for <%=current_user.first_name%> </h1>
    <p>Search for the world's best products, find them nearby!</p>
  </div>
</div>
<%@user_location = request.location%>
<h1 class="m-4"><%= pluralize(@counter, "Result") %></h1>
<div class="d-flex justify-content-center container" style="background-color: white; height: 100%; width: 100vw">
  <div class="d-flex flex-wrap container" style="margin-left: 1vw; margin-right: 1vw; background-color: white; height: 100%; width: 100vw">
  <% if @counter > 0 %>
      <% @products.each do |product| %>
        <div class="card" style="width: 20rem; height: 36rem; margin: 4vh auto; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
              <% if product.photos[0]!=nil %>
                <%= cl_image_tag product.photos[0].key, height: 300, width: 300, crop: :fill, class:"card-img-top bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
              <%else%>
                <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="" style="height: 300px; width: 319px;">
              <% end %>
              <div class="card-body">
                <h4 class="card-text"><%= product.brand %>, <%= product.name %></h4>
                <div class="d-flex ">
                  <div class=" align-items-center">
                    <div class="" style="margin-bottom: -10px">
                      <h4><span><i class="fa-solid fa-tag"></i></span> £<%= "%.2f" % product.price.round %></h4>
                      <p><i class="fa-solid fa-compass-drafting"></i> Distance: <%=  "%.1f" % Geocoder::Calculations.distance_between([current_user.location.latitude, current_user.location.longitude], [product.latitude, product.longitude]).round%>km</p>
                    </div>
                    <p style="margin-bottom:-2px;"><i class="fa-solid fa-clock"></i> <%= product.business.opening_time.strftime("%H:%M")%> - <%= product.business.closing_time.strftime("%H:%M")%><p>
                    <% if product.availability  %>
                      <span class="badge bg-success badge-pill badge-success">In stock</span>
                    <% else %>
                      <span class="badge bg-warning badge-pill badge-success">Out of stock</span>
                    <% end %>
                  </div>
                </div>
                  <div style="margin-top: -3px;">
                    <%= link_to "See up close!", product_show_path(product), class: "blue-btn" %>
                  </div>
                  <div style="margin-top: 20px">
                    <%= link_to "Add to my itinerary + ", create_itinerary_path(product, itinerary: {name: "My itinerary ##{current_user.saved_itineraries.all.count + 1}", status: false}), class: "blue-btn" %>
                  </div>
              </div>
            </div>
      <% end %>
        </div>
  <% else %>
      <div class="container d-flex justify-content-center" style="height: 50vh">
        <div class="align-self-center d-flex flex-column align-items-center justify-content-center">
          <h2><i class="fa-solid fa-hand-point-up"></i></h2>
        <div class= "d-flex flex-row align-items-center">
          <h3 class="mb-4" style="text-align:center">No results found, keep seeking.</h3>
        </div>
      </div>
    </div>
    <% end %>

    </div>
  </div>
</div>

app/views/itineraries/show.html.erb
<div data-controller="itinerary-show" style="height:max-content">

    <div style="width: 100%; height: 500px;"
      data-controller="map"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      <div data-itinerary-show-target = "geojson" data-map-target="geojson" data-geojson="" data-trigger="" data-setpoints="" data-action="change->map#buildRoute"></div>
      <input type="hidden" data-itinerary-show-target="userCurrentLocation" value="<%=current_user.location.longitude%>,<%=current_user.location.latitude%>">
    </div>

    <div class="container">
      <div class="container mt-3 p-3 card mb-3">
        <div data-itinerary-show-target = "nameContainer">
          <h1 data-itinerary-show-target="name"><%= @itinerary.name %>&nbsp<span style="font-size:20px" data-action="click->itinerary-show#displayNewNameForm"><i class="fa-solid fa-pencil"></i></span></h1>
          <%= simple_form_for @itinerary, url: update_element_path(@itinerary, "name") , html: {class: "d-flex flex-row align-content-center justify-content-between d-none", data: { itinerary_show_target: "newNameForm", action: "submit->itinerary-show#updateName"}} do |f| %>
            <%= f.input :name, label: false %>
            <input type="hidden" value="<%= @itinerary.id%>" data-itinerary-show-target="itineraryId">
            <%= f.submit "Change name", class: "btn btn-dark h-50" %>
          <% end %>
        </div>
        <p>The itinerary is schedualed for <strong><span data-itinerary-show-target="date"><%= @itinerary.saved_itineraries.first.date %></strong></span> <span data-action="click->itinerary-show#displayDateForm" data-itinerary-show-target="datePencil"><i class="fa-solid fa-pencil"></i></span></p>
        <%= simple_form_for @itinerary.saved_itineraries.first, url: update_element_path(@itinerary.saved_itineraries.first, "date") , html: {class: "d-flex flex-row align-content-center justify-content-between d-none", data: { itinerary_show_target: "dateForm", action: "submit->itinerary-show#updateDate"}} do |f| %>
            <%= f.input :date, label: false, html5:true %>
            <input type="hidden" value="<%= @itinerary.saved_itineraries.first.id%>" data-itinerary-show-target="savedItineraryId">
            <%= f.submit "Save", class: "btn btn-dark h-50" %>
          <% end %>
        <p>
        <div class="d-flex flex-column">
          <p><i class="fa-solid fa-clock"></i> Total travel time: <span data-itinerary-show-target="time"></span> hours</h3>
          <p><i class="fa-solid fa-road"></i> Total distance: <span data-itinerary-show-target="distance"></span> kilometers </h3>
        </div>
         <div class="d-flex flex-wrap flex-row justify-content-between align-items-center p-3">
            <div>
            <%= link_to "Add a customize stop", itinerary_stops_path(@itinerary), class: "btn btn-primary", style: "background-color:#2997D8 ; border-color:#2997D8 ;" %>
           </div>
            <div>
            <%= link_to "Add more products", add_products_path(@itinerary), class: "btn btn-primary", style: "background-color:#2997D8 ; border-color:#2997D8 ;" %>
           </div>
           <% if @itinerary.current%>
           <div>
            <%= link_to "Undo current", remove_as_current_path(@itinerary, itinerary: {current: false}), class: "btn btn-danger", style: "color:white", data: {turbo_method: :patch} %>
            </div>
           <% elsif SavedItinerary.has_current?(current_user.itineraries)%>
           <div>
              <%= link_to "Set as current", undo_and_set_as_current_path(@itinerary, itinerary: {current: true}), class: "btn btn-success", data: {turbo_method: :patch}, class: "btn btn-primary", style: "background-color:#2997D8 ; border-color:#2997D8 ;" %>
           </div>
           <% else %>
             <div>
              <%= link_to "Set as current", set_as_current_path(@itinerary, itinerary: {current: true}), data: {turbo_method: :patch}, class: "btn btn-primary ms-2 mb-4", style: "background-color:#2997D8 ; border-color:#2997D8 ;" %>
           </div>
           <% end %>
           <div>
           <%= link_to mark_as_complete_path(@itinerary, itinerary: {status: true}), class: "btn btn-success", data: {turbo_method: :patch, turbo_confirm: "Are you sure?"} do %>
            <p style="margin-bottom: 0 !important;">Mark as completed <i class="fa-solid fa-circle-check"></i></p>
           <% end %>
           </div>
         </div>
          <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <label class="btn btn-secondary active" data-action= "click->itinerary-show#getRouteForCycling">
              <input type="radio" name="options" autocomplete="off" checked>
                Cycling <i class="fa-solid fa-bicycle"></i>
            </label>
            <label class="btn btn-secondary" data-action= "click->itinerary-show#getRouteForWalking">
              <input type="radio" name="options" autocomplete="off" >
                Walking <i class="fa-solid fa-person-walking"></i>
            </label>
            <label class="btn btn-secondary" data-action= "click->itinerary-show#getRouteForCar">
              <input type="radio" name="options" autocomplete="off">
                Car <i class="fa-solid fa-car"></i>
            </label>
          </div>

        </p>
        <div class="d-flex flex-column p-3" style="max-height: fit-content;">
          <h4>Your itinerary stops; feel free to change the order.</h4>
          <ul data-itinerary-show-target="listProducts" data-action="change->itinerary-show#getRouteForCycling" >
            <% @itinerary.products.each do |product| %>
              <li style="list-style-type: none;" data-itinerary-show-target="product" data-type="product">
                <div id="itinerary-cards" class="card-product m-3" >
                  <% if product.photos[0]!=nil %>
                    <%= cl_image_tag product.photos[0].key, height: 300, width: 300, crop: :fill, class:"card-img-top bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
                  <%else%>
                    <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="" style="height: 300px; width: 319px;">
                  <% end %>
                  <div class="card-product-infos">
                    <h2 style="color:black"><%= "#{product.name} #{product.brand}" %> <a href="<%=business_product_path(product.business, product)%>"><span><i class="fa-solid fa-circle-info"></i> </span></a></h2>
                    <p style="color:black"><i class="fa-solid fa-location-dot"></i> <%= product.business.address %></p>
                    <p style="color:black"><i class="fa-solid fa-store"></i> <%= link_to product.business.name, business_path(product.business) %></p>
                    <input type="hidden" data-itinerary-show-target = "latitude" value="<%=product.business.latitude%>">
                    <input type="hidden" data-itinerary-show-target = "longitude" value="<%=product.business.longitude%>">
                  </div>
                  <div>
                    <%= link_to "See this product!", product_show_path(product), class: "blue-btn p-2"%>
                  </div>
                </div>
              </li>
            <% end %>
            <% @stops.each do |stop|%>
             <li style="list-style-type: none;" data-itinerary-show-target="stop" data-type="stop">
                <div class="card-product m-3">
                  <img src="https://images.dailyhive.com/20170815113327/Free-Wi-Fi-indicated-on-rest-area-sign-Province-of-BC.jpg" />
                  <div class="card-product-infos">
                    <h2 style="color:black"><%=stop.name%></h2>
                    <p><i class="fa-solid fa-location-dot"></i> <%= stop.address %></p>
                    <input type="hidden" data-itinerary-show-target = "latitude" value="<%=stop.latitude%>">
                    <input type="hidden" data-itinerary-show-target = "longitude" value="<%=stop.longitude%>">
                  </div>
                  <div>

                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
</div>
<div>
</div>
<div>


</div>