config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/owner", to: "pages#owner"

  resources :users, only: [:show]
  resources :locations, only: [:create, :update]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :businesses do
    resources :products
  end

  post "/businesses", to: "business#create", as: "post_business"

  get "/products", to: "products#list_all"
  get "/products/:id", to: "products#show_selected", as: "product_show"

  resources :itineraries, only: [:new, :update]
  get "/itineraries/:product_id/generate", to: "itineraries#create", as: "create_itinerary"
  get "/my_itineraries", to: "itineraries#index", as: "my_itinerary"
  get "/my_itineraries/:id", to: "itineraries#show", as: "my_itineraries"
  get "/my_itineraries/:id/add_products", to: "itineraries#add_products", as: "add_products"
  patch "/my_itineraries/:id/update/:element", to: "itineraries#update_element", as: "update_element"
  post "my_itineraries/product/:product_id/:itinerary_id/add", to: "itineraries#add_product_to_itinerary", as: "add_product_to_itinerary"
  delete "my_itineraries/product/:product_id/:itinerary_id/remove", to: "itineraries#remove_product_of_itinerary", as: "remove_product_of_itinerary"
  get "my_itineraries/:itinerary_id/get_itinerary", to: "itineraries#itinerary_route", as: "itinerary_route"
  get "my_itineraries/:id/add_stop/new", to: "stops#new", as: "itinerary_stops"
  post "my_itineraries/:id/add_stop/new", to: "stops#create", as: "itinerary_stops_create"
  patch "my_itineraries/:id/completed", to: "itineraries#mark_itinerary_as_completed", as: "mark_as_complete"
  get "history", to:"itineraries#history_itineraries", as: "history_itineraries"
  patch ":id/undo_and_set_current", to: "itineraries#undo_and_set_as_current", as: "undo_and_set_as_current"
  patch ":id/set_as_current", to: "itineraries#set_as_current", as: "set_as_current"
  patch ":id/remove_as_current", to: "itineraries#remove_as_current", as: "remove_as_current"
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  CATEGORY_LIST = [
    "Automotive", "Business Support & Supplies", "Computers & Electronics", "Construction & Contractors",
    "Education", "Entertainment", "Food & Dining", "Health & Medicine", "Home & Garden", "Legal & Financial",
    "Manufacturing, Wholesale,Distribution", "Merchants (Retail)", "Miscellaneous", "Personal Care & Services",
    "Real Estate", "Travel & Transportation","Sports"
  ]
  def new
    @business = Business.new
    @category_list = CATEGORY_LIST
  end

  def create
    @business = Business.new(business_params)
    @owner = current_user
    @business.owner = @owner

    if @business.save
      redirect_to businesses_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @business = Business.find(params[:id])
    @category_list = CATEGORY_LIST
  end

  def update
    @business = Business.find(params[:id])
    if @business.update(business_params)
      redirect_to business_path(@business)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def delete
    @business = Business.find(params[:id])
    @business.delete
    redirect_to businesses_path
  end

  def index
    @businesses = current_user.businesses
  end

  def show
    @business = Business.find(params[:id])
    @photos = @business.photos
    @markers = [{
      lat: @business.latitude,
      lng: @business.longitude
  }]
  end

  private

  def business_params
    params.require(:business).permit(:name, :address, :opening_time, :closing_time, :status, :category, :description, photos: [])
  end
end

app/views/businesses/edit.html.erb
<div class="m-4">
  <%= link_to "Go back to business!", business_path(@business), class: "blue-btn"%>
</div>
<div class="container">
  <h1>Edit business</h1>
  <div class="container card border p-3">
    <%= simple_form_for(@business) do |f|%>
    <%= f.input :address,
                input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
    <%= f.input :name %>
    <%= f.input :category, collection: @category_list %>
    <%= f.input :opening_time, as: :time, html5: true %>
    <%= f.input :closing_time, as: :time, html5: true %>
    <%= f.input :description %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit "Edit my business", class: "btn btn-primary", style: "background-color: #2997D8; border: 1px solid #2997D8; border-radius: 0px !important"%>
    <% end %>
  </div>
</div>

app/views/businesses/index.html.erb
<div class="banner d-flex align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/8475170/pexels-photo-8475170.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2);">
  <% if current_user == @businesses.first.owner%>
  <div id="banner-content"class="container">
    <h1 style="width: 25vw;"> <%=@businesses.first.owner.first_name%>'s businesses</h1>
    <p>Listed for seeking and ready to be discovered!</p>
  </div>
  <% else %>

  <div id="banner-content" class="container">
    <h1>Products from <%=@businesses.first.owner.first_name%></h1>
    <p>Search through the world's best products, find them nearby!</p>
  </div>
  <% end %>
</div>

<div class="m-4">
  <%= link_to "Back to profile", root_path, class: "blue-btn"%>
</div>
<% if @businesses.length > 0 %>
  <div  class="d-flex justify-content-center container" style="background-color: white; height: 100%; width: 100vw">
      <div class="d-flex flex-wrap container" style="margin-left: 1vw; margin-right: 1vw; background-color: white; height: 100%; width: 100vw;">
        <% @businesses.each do |business| %>
          <div class="card" style="width: 20rem; height: 31rem; margin: 4vh auto; box-shadow: 0 0 15px rgba(0,0,0,0.2);">
            <% if business.photos.attached?%>
              <%= cl_image_tag business.photos[0].key, height: 300, width: 300, crop: :fill, class:"card-img-top bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
            <% else %>
              <img src="https://www.fintelgaseluce.it/wp-content/uploads/2015/07/FEG-facebook-placeholder_shop.png" style="height: 300px; width: 319px;"/>
            <% end %>
            <div class="card-body">
              <h4 class="card-text"> <%= business.name %></h4>
              <div class="d-flex ">
                <div class=" align-items-center">
                  <p style="max-height: 25px; text-overflow: ellipsis;"><i class="fa-solid fa-address-book"></i> <%= business.address.first(20) %>...</p>
                  <p><i class="fa-solid fa-circle-question"></i><%= business.category %></p>
                </div>
              </div>
              <div style="margin-top: 10px">
                <%= link_to "See/edit this business!", business_path(business), class: "blue-btn"%>
              </div>
              </div>
          </div>
        <% end %>
      </div>
      <hr>
  </div>
<% else %>
    <div class="container d-flex justify-content-center" style="height: 50vh">
          <div class="align-self-center d-flex flex-column align-items-center justify-content-center">
            <h2><i class="fa-solid fa-hand-point-up"></i></h2>
          <div class= "d-flex flex-row align-items-center">
            <h3 class="mb-4" style="text-align:center">Create your first business, seekers are awaiting!</h3>
          </div>
        </div>
  </div>
<% end %>

app/views/businesses/new.html.erb
<div class="owner-page">
  <div class="owner-page-message">
    <h1 style=" font-weight:bold">This is your opportunity</h1>
    <h2 style=" font-weight:bold">Run your business</h2>
    <h3 class="new-owner-page-h3">Seekers are waiting for you..</h3>
  </div>
  <div class="new-business-form" style="box-shadow: 0 20px 50px rgba(0,0,0,.8);">
      <div class="row d-flex justify-content-center">
        <div class="col-10 mt-3 mb-3">
            <%= simple_form_for(@business) do |f|%>
            <%= f.input :address,
                        input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
            <%= f.input :name %>
            <%= f.input :category, collection: @category_list %>
            <%= f.input :opening_time, as: :time, html5: true %>
            <%= f.input :closing_time, as: :time, html5: true %>
            <%= f.input :description %>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            <%= f.submit "Make my business seekable", style:"background-color: #2997D8; color:white", class: "btn"%>
            <% end %>
        </div>
      </div>
    </div>
</div>

app/views/businesses/show.html.erb
<%@user_location = request.location%>
<div id="show-container" style="width: 100vw; background-color:white;">

  <div class="d-flex justify-content-around">

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel" style="height: 35vh; width: 100vw; ">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="4" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner" style="height: 35vh;" >

        <div class="carousel-item active" style="height: 35vh;  width: 100vw;">
          <% if @photos[0]!=nil %>
            <%= cl_image_tag @photos[0].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-start">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[1]!=nil %>
            <%= cl_image_tag @photos[1].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[2]!=nil %>
            <%= cl_image_tag @photos[2].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[3]!=nil %>
            <%= cl_image_tag @photos[3].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[4]!=nil %>
            <%= cl_image_tag @photos[4].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true" ></span>
        <span class="visually-hidden">Previous</span>
      </button>

      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>

      <div id="wide-buttons" style="margin-top: 10px; margin-left: -4.5px;">

        <% if current_user && current_user == @business.owner %>
          <div class="">
            <div class="d-flex" style="margin-bottom: 15px">
              <div class="m-1">
                <%= link_to "Go back to businesses!", businesses_path, class: "blue-btn"%>
              </div>
              <div class="m-1">
                <%= link_to "Edit your business details!", edit_business_path(@business), class: "blue-btn"%>
              </div>
              <div class="m-1">
                <%= link_to "See products!", business_products_path(@business), class: "blue-btn"%>
              </div>
            </div>
            <div class="d-flex">
              <div class="m-1">
                <%= link_to "Delete", business_path(@business), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "blue-btn", style: "background-color: red"%>
              </div>
            </div>
          </div>
        <% else %>
          <div class="d-flex align-items-center">
            <div class="m-1">
              <%= link_to "See products!", business_products_path(@business), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>
        <% end %>

      </div>

    </div>
  </div>

  <div id=info-container-picture-business-product-show class="d-flex justify-content-center pt-3" style= "width: 100vw; background-color: white">

    <div class="" style=" width: 95vw; ">

      <div class="m-2" style="bottom: 0; right: 0">

        <div class="mt-1">
          <h2 style="font-weight: bold"><i class="fa-solid fa-shop"></i> <%= @business.name %></h2>
          <hr>
          <p><i class="fa-solid fa-circle-question"></i> <%= @business.category %></p>
          <p><i class="fa-solid fa-address-book"></i> <%= @business.address %></p>
          <p><i class="fa-solid fa-door-open"></i> <%= @business.opening_time.strftime("%H:%M") %></p>
          <p><i class="fa-solid fa-door-closed"></i> <%= @business.closing_time.strftime("%H:%M") %></p>
          <% if user_signed_in? %>
            <p><i class="fa-solid fa-compass-drafting"></i> <%= "%.2f" % Geocoder::Calculations.distance_between([current_user.location.latitude, current_user.location.longitude], [@business.latitude, @business.longitude])%>km</p>
          <% end %>
        </div>

      </div>

      <div class="m-2">
        <h2>About <%= @business.name %></h2>
        <p><i class="fa-solid fa-list"></i> <%= @business.description%></p>
      </div>

      <div id="narrow-buttons">

        <% if current_user && current_user == @business.owner %>

            <div class="d-flex align-items-center flex-wrap">
              <div class="m-2">
                <%= link_to "To businesses!", businesses_path, class: "blue-btn"%>
              </div>
              <div class="m-2" style="margin-top: 20px">
                <%= link_to "Edit business!", edit_business_path(@business), class: "blue-btn"%>
              </div>
              <div class="m-2">
                <%= link_to "See products!", business_products_path(@business), class: "blue-btn"%>
              </div>
              <div class="m-2">
                <%= link_to "Back", :back, class: "blue-btn" %>
              </div>
              <div class="m-2">
                <%= link_to "Delete", business_path(@business), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "blue-btn", style: "background-color: red"%>
              </div>
            </div>

        <% else %>
          <div class="d-flex align-items-center">
            <div class="m-1">
              <%= link_to "See products!", business_products_path(@business), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>
        <% end %>
        <hr>
      </div>

        <div id="show-map" class="map" style="width: 100%; height: 30vh; border-radius-button: 10px; margin-bottom: 5vh;"
          data-controller="map-show"
          data-map-show-markers-value="<%= @markers.to_json %>"
          data-map-show-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

    </div>

  </div>

</div>