config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/owner", to: "pages#owner"

  resources :users, only: [:show]
  resources :locations, only: [:create, :update]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :businesses do
    resources :products
  end

  post "/businesses", to: "business#create", as: "post_business"

  get "/products", to: "products#list_all"
  get "/products/:id", to: "products#show_selected", as: "product_show"

  resources :itineraries, only: [:new, :update]
  get "/itineraries/:product_id/generate", to: "itineraries#create", as: "create_itinerary"
  get "/my_itineraries", to: "itineraries#index", as: "my_itinerary"
  get "/my_itineraries/:id", to: "itineraries#show", as: "my_itineraries"
  get "/my_itineraries/:id/add_products", to: "itineraries#add_products", as: "add_products"
  patch "/my_itineraries/:id/update/:element", to: "itineraries#update_element", as: "update_element"
  post "my_itineraries/product/:product_id/:itinerary_id/add", to: "itineraries#add_product_to_itinerary", as: "add_product_to_itinerary"
  delete "my_itineraries/product/:product_id/:itinerary_id/remove", to: "itineraries#remove_product_of_itinerary", as: "remove_product_of_itinerary"
  get "my_itineraries/:itinerary_id/get_itinerary", to: "itineraries#itinerary_route", as: "itinerary_route"
  get "my_itineraries/:id/add_stop/new", to: "stops#new", as: "itinerary_stops"
  post "my_itineraries/:id/add_stop/new", to: "stops#create", as: "itinerary_stops_create"
  patch "my_itineraries/:id/completed", to: "itineraries#mark_itinerary_as_completed", as: "mark_as_complete"
  get "history", to:"itineraries#history_itineraries", as: "history_itineraries"
  patch ":id/undo_and_set_current", to: "itineraries#undo_and_set_as_current", as: "undo_and_set_as_current"
  patch ":id/set_as_current", to: "itineraries#set_as_current", as: "set_as_current"
  patch ":id/remove_as_current", to: "itineraries#remove_as_current", as: "remove_as_current"
end

app/views/shared/_current_address_setting.html.erb
<div style="">
  <% if current_user.location.presence == nil %>
    <%# <p>
      <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Set current location
      </a>
    </p> %>
    <div class="collapse" id="collapseExample">
      <%= simple_form_for Location.new, data: {turbo: false} do |f|%>
        <div class="current-location-input-form">
          <%= f.input :address, class:"", required: true, label:false, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
          <div class="">
            <%= f.button :submit, "Set", class:"current-location-input-form-submit btn btn-dark" %>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="d-flex justify-content-around">

    </div>
    <div style="" class="collapse" id="collapseExample">
    <%= simple_form_for (current_user.location), data: {turbo: false} do |f|%>
      <div class="current-location-input-form">
        <%= f.input :address, class:"", required: true, label:false, input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
        <%= f.button :submit, "Change", class:"current-location-input-form-submit btn btn-dark", style:"" %>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_dropdown_icon_navbar.html.erb
<div class="dropdown-icon" style="">
  <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "Edit", edit_user_registration_path, class: "dropdown-item" %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </div>
    </li>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="blue" style="height: 26vh; color:white; position-relative; bottom:0px;">
  <div class="d-flex justify-content-center" style ="width:100vw;">
    <div class="d-flex align-items-center" style="margin-top: 5vh;">
      <div>
          <h6>Home</h6>
          <h6>Help</h6>
          <h6>Work with us</h6>
      </div>
      <div style ="width: 20vw;">
      </div>
      <div>
          <h6>About</h6>
          <h6>Terms</h6>
          <h6>Guideline</h6>
      </div>
    </div>
  </div>
    <div style="width: 100vw;"class="d-flex justify-content-center">
        <div style="width: 100px;" class="d-flex justify-content-around">
          <i class="fa-brands fa-twitter"></i>
          <i class="fa-brands fa-facebook"></i>
          <i class="fa-brands fa-instagram"></i>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-2">
      <%= link_to "Seekr.com", root_path, style:"text-decoration:none; color:white; font-size:20px;"  %>
    </div>
</div>

app/views/shared/_landing_header.html.erb
<div style="background-color: #2997D8;" class="d-flex justify-content-center">
  <div class="landing-header-container" style="text-align:center">
    <div>
    <h2 style=" font-weight: bold; color:white; margin-top:130px ">Find anything on the highstreet</h2>

      <div class="" style=" width: 400px;">
         <%= simple_form_for :filters, url: products_path, method: :get do |f| %>
        <%= f.input :seek, placeholder: 'Categories, product name..', label: false,  class:"seek-search" %>
        <div class="nav-search" style="border-radius: 15px" >
          <%= f.input :address, label: false, input_html: {data: {address_autocomplete_target: "address"}, class: "mapboxgl-ctrl-geocoder--input d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
          <%= button_tag type: 'submit', class:"signed-out-search-glass-container btn" do %>
            <i class="fa-solid signed-out-search-glass fa-magnifying-glass"></i>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
    <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671059995/pibr2jpoptvwzj6zpauk.png" class="iphone-image ms-4 mt-4">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="d-flex landing-navbar navbar navbar-expand-sm navbar-light navbar-lewagon" style=" background-color:#2997D8;">
  <%= link_to "/", class: "navbar-brand" do %>
      <h1 style="font-weight: bold; color:white; margin-left: 2vw;" >Seekr</h1>
  <% end%>
  <%= render "shared/signed_in_PC_navbar_search" %>
  <% if user_signed_in? %>
    <div class="humberger-nav">
      <label class="toggle" for="open">
        <i class="fa fa-bars" style="color: white; font-size: 40px;" aria-hidden="true"></i>
      </label>
      <input id="open" type="checkbox">
      <%= render "shared/slidebar_mobile" %>
    </div>

    <%# icon-navbar %>
    <%= render "components/icon_navbar" %>

  <% else %>
    <div class="d-flex" style="color:white">
      <li class="nav-item me-4">
        <%= link_to "Signup", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item me-2">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    </div>
  <% end %>

</div>

app/views/shared/_product_card.html.erb
<%= @products.each do| product|%>
<div class = "card d-flex">
  <div><img src=# /></div>
  <div>
    <h4><%= product.name  %>
    <p><i class="fa-solid fa-star"></i>Brand: <%= product.brand%></p>
    <p><i class="fa-solid fa-circle-question"></i> Category :<%= product.category %></p>
    <p><i class="fa-solid fa-tag"></i>Price: £<%= product.price.round%><p>
  <div>
  <div>
    <%= link_to "See item!",  business_product_path(@business, product), class:"btn btn-dark"%>
  </div>
</div>
<%end%>

app/views/shared/_signed_in_PC_navbar_search.html.erb
<% if ((user_signed_in? && (controller_name == "pages" || (controller_name == "itineraries" && (action_name == "new" || action_name == "add_products") ))) || controller_name == "products")  %>
  <div style="text-align:center">
    <div class="sign-in-search-engine-pc-tablet">
      <!-- The following form displays if adding more products -->
      <% if ((controller_name == "itineraries" && action_name == "add_products") || controller_name == "products" && action_name=="list_all" ) %>
        <%= simple_form_for :filters, method: :get do |f| %>
          <div class="d-flex">
            <%= f.input :seek, input_html: {class: "seek-search"}, placeholder: 'Categories, product name..', label: false %>
            <div class="d-flex" style="height: 37px;" >
            <%= f.input :address, label: false, input_html: {data: {address_autocomplete_target: "address"}, class: "mapboxgl-ctrl-geocoder--input d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
            <%= button_tag type: 'submit', class:"glass-btn btn me-5" do %>
              <i style="" class="fa-solid fa-magnifying-glass"></i>
            <% end %>
          </div>
          </div>
        <% end %>
      <!-- The following form will be displayed if creating a new itinerary instance -->
      <% else %>
        <%= simple_form_for :filters, url: new_itinerary_path, method: :get do |f| %>
          <div class="d-flex">
            <%= f.input :seek, input_html: {class: "seek-search"}, placeholder: 'Categories, product name..', label: false %>
            <div class="d-flex" style="height: 37px;" >
            <%= f.input :address, label: false, input_html: {data: {address_autocomplete_target: "address"}, class: "mapboxgl-ctrl-geocoder--input d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
            <%= button_tag type: 'submit', class:"glass-btn btn me-5" do %>
              <i style="" class="fa-solid navbar-search-glass fa-magnifying-glass"></i>
            <% end %>
          </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_signed_in_home.html.erb
<div class="d-flex mb-4" style="" >
  <%# left side container %>
  <%= render "components/signed_in_sidebar" %>

  <%# right side conatainer %>
  <%# dashbored 1 %>
  <div class="sign-in-right-container" style="">

    <%# search engine %>
    <div style="" class="blue" id="sign-in-search-engine">
      <%= simple_form_for :filters, url: new_itinerary_path, method: :get do |f| %>
        <%= f.input :seek, placeholder: 'Categories, product name..', label: false,  class:"seek-search" %>
        <div class="nav-search" style="border-radius: 15px" >
          <%= f.input :address, label: false, input_html: {data: {address_autocomplete_target: "address"}, class: "mapboxgl-ctrl-geocoder--input d-none"}, wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}%>
          <%= button_tag type: 'submit', class:"signed-in-search-glass-container btn" do %>
            <i class="fa-solid signed-in-search-glass fa-magnifying-glass"></i>
          <% end %>
        </div>
      <% end %>
    </div>


    <div style="width:100%;">
      <%# #f6db04 #f6ff58 %>
      <div class="mt-3 corner dashbored-name-address" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); margin: 0 auto; width:80%; background-color:#333">
        <%= render "components/display_setting_address" %>
        <%= render "shared/current_address_setting" %>
        <hr>
        <div class="dashbrod-detail d-flex justify-content-around">
          <%= render "components/dashbored_detail" %>
        </div>
      </div>
    </div>

    <%# category list %>
    <div style="text-align:center; background-size:cover; background-image:url('https://img.freepik.com/free-photo/full-length-portrait-excited-man_171337-2333.jpg?w=1480&t=st=1670527180~exp=1670527780~hmac=3e611183adee5f13ea9058d251f88ddaeff590430b12b5b1c17362ba4a8690dc')">
        <h3 class="mt-5" style="font-weight:bold;">Find your item</h3>
        <div style="margin-top:200px">
          <div style="text-align:center; background: #333; width:100%;">
            <h3 style="padding-bottom:8px; padding-top:8px; font-weight:bold; color:white">Categories</h3>
          </div>
          <%= render "shared/slide_home_link_category" %>
        </div>
    </div>
      <%= render "shared/slide_home_link_near_shops" %>

  </div>
</div>

app/views/shared/_slide_home_link_category.html.erb
<div class="home-card-slide col-lg-3 d-flex row flex-row flex-nowrap overflow-auto" style="z-index:10; margin: 0 auto; width: 100%">

  <%= link_to new_itinerary_path(:filters => {:seek => "sports", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style=" width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card mb-3 card-text">Sports</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/stretching-exercises-concept-illustration_114360-9072.jpg?w=1480&t=st=1671118128~exp=1671118728~hmac=e22d16862bee497709ef14a5232d012ef76ca604bc539c250aaa0a4ab3d49314" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Travel", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Travel</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/taipei-concept-illustration_114360-5781.jpg?w=1480&t=st=1671117314~exp=1671117914~hmac=c969b7f6e62a809fec2bf47b4c7dd2c9a8409d1ff4086f9cf3d38f02ea38d984" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Medical", :address => @current_location }), class:"home-category-links", class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Medical</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/medicine-concept-illustration_114360-1555.jpg?w=1480&t=st=1670522060~exp=1670522660~hmac=5adf320261fe70dbefbca468c5defb4da1d1be22081767a87c05c7b988d95b2e" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Clothes", :address => @current_location }),class:"home-category-links",  style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Clothes</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/flat-hand-drawn-flea-market-illustration_23-2148848377.jpg?size=626&ext=jpg&uid=R87380621&ga=GA1.2.464133550.1670521750&semt=sph" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Tech", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Tech</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/isometric-cms-concept_23-2148807389.jpg?w=1480&t=st=1670522201~exp=1670522801~hmac=ff96e4a8ec3210493f32431c4ef59aafe26d8be5fbf5a784bffd1126d6b52561" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Study", :address => @current_location }), class:"home-category-links",  style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Study</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/studying-concept-illustration_114360-1107.jpg?w=1480&t=st=1670522234~exp=1670522834~hmac=47a9b60ad6e4cccef576d2932213265ebafcb22a01de134c4dbc4c43a6dbd96d" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Cooking", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Cooking</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/male-chef-mixing-flour-eggs-dough-with-whisk-hands-happy-man-apron-preparing-homemade-sweet-dessert-table-home-kitchen-flat-vector-illustration-pastry-cooking-recipe-concept_74855-21965.jpg?w=1480&t=st=1670523561~exp=1670524161~hmac=16294fa75dddebe0aed8b2e49d869d4d8b48e1935713edd612c0e985aeb0852b" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Food", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Food</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/choosing-healthy-unhealthy-food_52683-39219.jpg?w=1480&t=st=1670524555~exp=1670525155~hmac=767310fb6d0acc35825110c2d4509cbc4203276dd4251360a7879249d8222a8e" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Furniture", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Furniture</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/furniture-store-concept-illustration_114360-6216.jpg?w=1480&t=st=1671117179~exp=1671117779~hmac=7e39067a2cb7aa293ef6acf5dea28decdd843e5c5f12795c9eda55b0a5a2ded8" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Books", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Books</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/hand-student-holding-magnifying-glass-studying-books-stack-books-scientific-research-flat-vector-illustration-education-information-concept-banner-website-design-landing-page_74855-24720.jpg?w=1480&t=st=1671117494~exp=1671118094~hmac=cc568b35b5d92bed2b54ee42376c6b3a2b56dd49e4d57c19550572a5a3563226" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Games", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Games</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/having-fun-concept-illustration_114360-1702.jpg?w=1480&t=st=1671117801~exp=1671118401~hmac=5e925ae9fb30e368b756788c43b1526974d4c52cb3db4824e462ea673d651486" class="card-img-top" alt="...">
    </div>
  <% end %>
  <%= link_to new_itinerary_path(:filters => {:seek => "Cleaning", :address => @current_location }), class:"home-category-links", style:"text-decoration:none; color:black; width:200px;" do %>
    <div class="corner card" style="width: 12rem;">
      <div class="home-card-slidecard-body card-body">
        <h5 style="font-weight:bold" class="category-card card-text">Cleaning</h5>
      </div>
      <img class="mt-3"style="width:100%" src="https://img.freepik.com/free-vector/cleaning-service-concept-illustration_114360-9842.jpg?w=1480&t=st=1671118467~exp=1671119067~hmac=655dc43a10c1be14c79d9c613a9d18ee3d08c4422aee8815b3a609dcd81e01aa" class="card-img-top" alt="...">
    </div>
  <% end %>

</div>

app/views/shared/_slide_home_link_near_shops.html.erb
<div class="mt-2 mb-2" style="text-align:center; background-color: #333; width:100%;">
  <h3 style="padding-bottom:8px; padding-top:8px; font-weight:bold; color:white">Shops near you</h3>
</div>


<% if current_user.location == nil %>
  <h5 style="text-align:center " class="mt-4 mb-4"> Set your location to see stores around you</h5>
<% elsif @shops == [] %>
  <h5 style="text-align:center " class="mt-4 mb-4"> Sorry... no shops around your current address at the moment..</h5>
<% else %>
  <% @shops.each do |shop| %>
    <%= link_to business_path(shop), style:"text-decoration:none; color:black" do  %>
    <div class="shops-near mt-2 d-flex" style=" border-bottom: solid 2px black">
      <% if shop.photos.attached?  %>
        <%= cl_image_tag shop.photos[0].key, height: 120, width: 120, class:"", crop: :fill %>
      <% else %>
        <img src="https://icons.veryicon.com/png/o/miscellaneous/zr_icon/company-23.png" style="height: 120px; width: 120px;"alt="">
      <% end %>
     <div class="home-business-detail" >
      <h3><%= shop.name %></h3>
      <p><%= shop.address %></p>
      <p>Open time <%= shop.opening_time.strftime("%H:%M") %>-<%= shop.closing_time.strftime("%H:%M") %></p>
     </div>
    </div>
    <% end %>

  <% end %>
<% end %>

app/views/shared/_slidebar_mobile.html.erb
<div id="menu">
  <div class="slide-avatar-container">
    <% if current_user.avatar.attached? %>
      <%= cl_image_tag current_user.avatar.key, crop: :fill, class:"side-bar-avatar  round" %>
    <% else %>
      <img class="round side-bar-avatar" style=""src="https://pcafalcons.com/wp-content/uploads/2019/08/no-profile-picture-icon-female-0-e1564976045606.jpg" alt="">
    <% end %>
    <br>
    <% if current_user.location.presence %>

    <% end %>
  </div>


  <% if current_user.location.present? %>
    <div class="mt-3 d-flex" style="color:white">
      <i class="fa-solid fa-location-dot"></i>
      <p class="ms-3"><%= current_user.location.address %></p>
    </div>
  <% end %>


  <nav>
    <ul>
      <%= link_to "My itineraries",  my_itinerary_path, class: "slide-bar-links dropdown-item" %>
      <%= link_to "My account", user_path(current_user), class: "slide-bar-links dropdown-item" %>
      <% if current_user.businesses.present? %>
        <%= link_to "My businesses", businesses_path, class:"slide-bar-links dropdown-item" %>
        <%= link_to "New business", new_business_path, class:"slide-bar-links dropdown-item"%>
      <% else %>
        <%= link_to "New business",new_business_path, class:"slide-bar-links dropdown-item"  %>
      <% end %>
      <%= link_to "Itineraries History", history_itineraries_path, class:"slide-bar-links dropdown-item"  %>
      <%= link_to "Edit account", edit_user_registration_path(current_user), class: "slide-bar-links dropdown-item" %>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "slide-bar-logout slide-bar-links dropdown-item" %>
    </ul>
  </nav>
</div>