config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/owner", to: "pages#owner"

  resources :users, only: [:show]
  resources :locations, only: [:create, :update]


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :businesses do
    resources :products
  end

  post "/businesses", to: "business#create", as: "post_business"

  get "/products", to: "products#list_all"
  get "/products/:id", to: "products#show_selected", as: "product_show"

  resources :itineraries, only: [:new, :update]
  get "/itineraries/:product_id/generate", to: "itineraries#create", as: "create_itinerary"
  get "/my_itineraries", to: "itineraries#index", as: "my_itinerary"
  get "/my_itineraries/:id", to: "itineraries#show", as: "my_itineraries"
  get "/my_itineraries/:id/add_products", to: "itineraries#add_products", as: "add_products"
  patch "/my_itineraries/:id/update/:element", to: "itineraries#update_element", as: "update_element"
  post "my_itineraries/product/:product_id/:itinerary_id/add", to: "itineraries#add_product_to_itinerary", as: "add_product_to_itinerary"
  delete "my_itineraries/product/:product_id/:itinerary_id/remove", to: "itineraries#remove_product_of_itinerary", as: "remove_product_of_itinerary"
  get "my_itineraries/:itinerary_id/get_itinerary", to: "itineraries#itinerary_route", as: "itinerary_route"
  get "my_itineraries/:id/add_stop/new", to: "stops#new", as: "itinerary_stops"
  post "my_itineraries/:id/add_stop/new", to: "stops#create", as: "itinerary_stops_create"
  patch "my_itineraries/:id/completed", to: "itineraries#mark_itinerary_as_completed", as: "mark_as_complete"
  get "history", to:"itineraries#history_itineraries", as: "history_itineraries"
  patch ":id/undo_and_set_current", to: "itineraries#undo_and_set_as_current", as: "undo_and_set_as_current"
  patch ":id/set_as_current", to: "itineraries#set_as_current", as: "set_as_current"
  patch ":id/remove_as_current", to: "itineraries#remove_as_current", as: "remove_as_current"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :business
  has_many :product_itineraries
  has_many_attached :photos
  has_many :itineraries, through: :product_itineraries

  include PgSearch::Model
  pg_search_scope :search_by_product,
                  against: [:name, :category, :brand],
                  using: {
                    trigram: {
                      word_similarity: true
                    }
                  }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def list_all
    seek = params[:filters].nil? ? "" : params[:filters][:seek]
    address = params[:filters].nil? ? "" : params[:filters][:address]
    query = search_engine(seek, address)
    @products = query[0]
    @counter = query[1]
  end

  def show_selected
    @product = Product.find(params[:id])
    @photos = @product.photos
    @markers = [{
      lat: @product.latitude,
      lng: @product.longitude
    }]
  end

  def index
    @business = params[:business_id]
    @products = Business.find(params[:business_id]).products
  end

  def show
    @product = Product.find(params[:id])
    @business = Business.find(params[:business_id])
    @photos = @product.photos

    @markers = [{
        lat: @product.latitude,
        lng: @product.longitude
    }]
  end

  def new
    @product = Product.new
    @business = Business.find(params[:business_id])
  end

  def create
    @product = Product.new(product_params)
    @business = Business.find(params[:business_id])
    @product.latitude = @business.latitude
    @product.longitude = @business.longitude
    @product.business = @business
    if @product.save
      redirect_to business_product_path(@business, @product)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
    @business = @product.business
  end

  def get_distance
    params[:geo]
  end

  def update
    @business = Business.find(params[:business_id])
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to business_product_path(@business, @product)
    else
      render :edit, :unprocessable_entity
    end
  end

  def destroy
    @business = Business.find(params[:business_id])
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to business_products_path(@business), status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:category, :brand, :price, :name, :description, :availability, photos: [])
  end

  def search_engine(seek, address)
    products = []
    if seek != "" && address != ""
      Product.search_by_product(seek).each do |product|
        Business.near(address, 20).each do |business|
          products << product if product.business == business
        end
      end
    elsif address != ""
      Business.near(address, 20).each do |business|
        business.products.each do |product|
          products << product unless product.nil?
        end
      end
    elsif seek != ""
      products = Product.search_by_product(seek)
    end
    return [products, products.count || 0] # Polimorfism!!!
  end
end

app/views/products/_fake.html.erb
<h1><%@product.name%></h1>
<div class="products_index_photo_container">
</div>

<div class="d-flex justify-content-left" style="height:600px;">
  <div>
  <div class="d-flex" style="box-shadow: 0 0 15px rgba(0,0,0,0.2); width: 90vw; border-radius: 15px;">
    <div class="mt-5 ms-5" style="bottom: 0; right: 0">
      <h2>Product info</h2>
      <p><i class="fa-solid fa-star"></i>Brand: <%= @product.brand%></p>
      <p><i class="fa-solid fa-circle-question"></i> Category :<%= @product.category %></p>
      <p><i class="fa-solid fa-tag"></i>Price: £<%= @product.price.round%>
      <% if current_user && current_user != @product.business.owner %>
      <div class="d-flex justify-content-center">
        <a href="#" class="btn btn-dark mt-3 me-2">Seek it!</a>
      </div>
      <% elsif current_user && current_user == @product.business.owner %>
        <div class="d-flex">
          <div class="m-1">
            <%= link_to "Edit this product!", edit_business_product_path(@business, @product), class: "btn btn-dark"%>
          </div>
          <div class="m-1">
            <%= link_to "Delete", business_product_path(@business, @product), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "btn btn-dark"%>
          </div>
        </div>
      <% end %>
    </div>
    <div style="width: 100vw; height: 100vh;">
      <div style="width: 100vw; height: 100vh;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
</div>

<div class="d-flex justify-content-center mt-4" style ="width:100vw">
  <div class="m-1">
    <%= link_to "Add new product", new_business_product_path,  class: "btn btn-dark"%>
  </div>
</div>

<% if current_user  %>
  <div class="d-flex justify-content-center">
    <%= link_to "Add to my itinerary + ", create_itinerary_path(@product, itinerary: {name: "My itinerary ##{current_user.saved_itineraries.all.count + 1}", status: false}), class: "blue-btn" %>
  </div>
<% else %>
  <div class="d-flex">
    <div class="m-1">
      <%= link_to "Add to my itinerary + ", create_itinerary_path(@product, itinerary: {name: "My itinerary ##{current_user.saved_itineraries.all.count + 1}", status: false}), class: "blue-btn" %>
    </div>
  </div>
<% end %>

    <div class="picture-holder-business-product-show d-flex"  width="45%" height="100%">

      <div class="double-picture-holder-business-product-show">
        <div class="small-picture-business-product-show">
          <img class="bd-placeholder-img c-image" width="100%" height="100%" src="https://k8q7r7a2.stackpathcdn.com/wp-content/uploads/2021/04/Rolex-Daytona-Meteorite-dial-white-gold-ceramic-bezel-oysterflex-bracelet-116519ln-6.jpg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false" style="width: 100%; height:100%">
        </div>
        <div class="small-picture-business-product-show">
          <img class="bd-placeholder-img c-image" width="100%" height="100%" src="https://k8q7r7a2.stackpathcdn.com/wp-content/uploads/2021/04/Rolex-Daytona-Meteorite-dial-white-gold-ceramic-bezel-oysterflex-bracelet-116519ln-6.jpg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false" style="width: 100%; height:100%">
        </div>
      </div>

      <div class="double-picture-holder-business-product-show">
        <div class="small-picture-business-product-show">
          <img class="bd-placeholder-img c-image" width="100%" height="100%" src="https://k8q7r7a2.stackpathcdn.com/wp-content/uploads/2021/04/Rolex-Daytona-Meteorite-dial-white-gold-ceramic-bezel-oysterflex-bracelet-116519ln-6.jpg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false" style="width: 100%; height:100%">
        </div>
        <div class="small-picture-business-product-show">
          <img class="bd-placeholder-img c-image" width="100%" height="100%" src="https://k8q7r7a2.stackpathcdn.com/wp-content/uploads/2021/04/Rolex-Daytona-Meteorite-dial-white-gold-ceramic-bezel-oysterflex-bracelet-116519ln-6.jpg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false" style="width: 100%; height:100%">
        </div>
      </div>

    </div>

  </div>
</div>
<div>
            <%= link_to "See this product!", product_show_path(product), class: "blue-btn"%>
            </div>

app/views/products/edit.html.erb
<div class="m-4">
  <%= link_to "Go Back to product", business_product_path([@business, @product]), class: "blue-btn"%>
</div>
<div class="container" style="margin-bottom: 2vh">
  <h1>Edit <%= @product.name%></h1>
  <%= simple_form_for([@business, @product]) do |f| %>
        <%= f.input :name %>
        <%= f.input :price, as: :float %>
        <%= f.input :category %>
        <%= f.input :brand %>
        <%= f.input :description %>
        <%= f.input :availability %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit class: "btn btn-primary", style: "background-color: #2997D8; border: none; border-radius: 0px !important" %>
      <% end %>
</div>

app/views/products/show.html.erb
<% @user_location = request.location %>
<div id="show-container" style="width: 100vw; background-color:white;">

  <div class="d-flex justify-content-around">

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel" style="height: 35vh; width: 100vw; ">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="4" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner" style="height: 35vh;" >

        <div class="carousel-item active" style="height: 35vh;  width: 100vw;">
          <% if @photos[0]!=nil %>
            <%= cl_image_tag @photos[0].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-start">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[1]!=nil %>
            <%= cl_image_tag @photos[1].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[2]!=nil %>
            <%= cl_image_tag @photos[2].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[3]!=nil %>
            <%= cl_image_tag @photos[3].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <% if @photos[4]!=nil %>
            <%= cl_image_tag @photos[4].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <%else%>
            <img src="https://res.cloudinary.com/dicqfpbyc/image/upload/v1671166248/j1v91gw4pkbelj5wfaq4.png" alt="">
          <% end %>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true" ></span>
        <span class="visually-hidden">Previous</span>
      </button>

      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>

      <div id="wide-buttons" style="margin-top: 10px; margin-left: -4.5px; margin-bottom: 50px;">
        <% if current_user && current_user == @product.business.owner %>
          <div class="d-flex aligin-items-center flex-wrap">
            <div class="m-2">
              <%= link_to "Go back to products!", business_products_path(@business), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Edit this product!", edit_business_product_path(@business, @product), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Delete", business_product_path(@business, @product), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>

        <% elsif current_user %>
          <div class="d-flex align-items-center flex-wrap">
            <div class="m-2">
              <%= link_to "Add to my itinerary + ", create_itinerary_path(@product, itinerary: {name: "My itinerary #{current_user.saved_itineraries.all.count + 1}", status: false}), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "See the business", business_path(@product.business), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "More from this seller", business_products_path(@product.business), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>
        <% else %>
            <div class="m-2">
              <%= link_to "Login to add this item to your itinerary", new_user_registration_path, class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>

        <% end %>
      </div>
    </div>
  </div>

  <div id="info-container-picture-business-product-show" class="d-flex justify-content-center pt-3" style="width: 100vw; background-color: white">
    <div class="" style=" width: 95vw; ">
      <div class="m-2" style="bottom: 0; right: 0">

        <div class="mt-1">
          <h2 style="font-weight: bold"><%=@product.name%></h2>
          <p style="font-weight: bold"><i class="fa-solid fa-shop"></i> Sold by: <%=@product.business.name%></p>
          <hr>
          <h2 style="margin-left: 5px; margin-top: 5px;" ><i class="fa-solid fa-tag"></i> Price: £<%= "%.2f" % @product.price.round%></h2>
          <p><i class="fa-solid fa-star"></i> Brand: <%= @product.brand%></p>
          <p><i class="fa-solid fa-circle-question"></i> Category :<%= @product.category %></p>
          <p><i class="fa-solid fa-compass-drafting"></i> Distance: <%=  "%.2f" % Geocoder::Calculations.distance_between([current_user.location.latitude, current_user.location.longitude], [@product.latitude, @product.longitude])%>km</p>
          <p><i class="fa-solid fa-clock"></i> <%= @product.business.opening_time.strftime("%H:%M")%> - <%= @product.business.closing_time.strftime("%H:%M")%><p>
        </div>

      </div>

      <div class="m-2">
        <h2>Product info</h2>
        <p><i class="fa-solid fa-list"></i> <%=@product.description%></p>
      </div>

      <div id="narrow-buttons">

        <% if current_user && current_user == @product.business.owner %>

          <div class="d-flex align-items-center flex-wrap">

            <div class="m-2">
              <%= link_to "Go back to products!", business_products_path(@business), class: "blue-btn"%>
            </div>

            <div class="m-2">
              <%= link_to "Edit this product!", edit_business_product_path(@business, @product), class: "blue-btn"%>
            </div>

            <div class="m-2">
              <%= link_to "Delete", business_product_path(@business, @product), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "blue-btn"%>
            </div>

            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>

          </div>

        <% elsif current_user%>
          <div class="d-flex align-items-center flex-wrap">

            <div class="m-2">
              <%= link_to "Add to my itinerary + ", create_itinerary_path(@product, itinerary: {name: "My itinerary #{current_user.saved_itineraries.all.count + 1}", status: false}), class: "blue-btn" %>
            </div>

            <div class="m-2">
              <%= link_to "See the business", business_path(@product.business), class: "blue-btn" %>
            </div>

            <div class="m-2">
              <%= link_to "More from this seller", business_products_path(@product.business), class: "blue-btn" %>
            </div>

            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>

          </div>
        <% else %>

          <div class="m-3">
            <%= link_to "Login to add this item to your itinerary", new_user_registration_path, class: "blue-btn"%>
          </div>

          <div class="m-">
            <%= link_to "Back", :back, class: "blue-btn" %>
          </div>

        <% end %>
        <hr>

      </div>

        <div id="show-map" class="map" style="width: 100%; height: 30vh; border-radius-button: 10px; margin-bottom: 5vh;"
          data-controller="map-show"
          data-map-show-markers-value="<%= @markers.to_json %>"
          data-map-show-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>

    </div>

  </div>

</div>

app/views/products/show_selected.html.erb
<div id="show-container" style="width: 100vw; background-color:white;">
  <div class="d-flex justify-content-around">

    <div id="myCarousel" class="carousel slide" data-bs-ride="carousel" style="height: 35vh; width: 100vw; ">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="3" aria-label="Slide 3"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="4" aria-label="Slide 3"></button>
      </div>

      <div class="carousel-inner" style="height: 35vh;" >
        <div class="carousel-item active" style="height: 35vh;  width: 100vw;">
          <%= cl_image_tag @photos[0].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <div class="container">
            <div class="carousel-caption text-start">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <%= cl_image_tag @photos[1].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l" , preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <div class="container">
            <div class="carousel-caption">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <%= cl_image_tag @photos[2].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l"  , preserveAspectRatio: "xMidYMid slice", focusable: "false"%>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <%= cl_image_tag @photos[3].key, height: 800, width: 800, crop: :fill, class:"bd-placeholder-img c-image-l", preserveAspectRatio: "xMidYMid slice", focusable: "false" %>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>

        <div class="carousel-item" style="height: 35vh">
          <%= cl_image_tag @photos[4].key, height: 600, width: 600, crop: :fill, class:"bd-placeholder-img c-image-l" , preserveAspectRatio: "xMidYMid slice", focusable: "false"%>
          <div class="container">
            <div class="carousel-caption text-end">
            </div>
          </div>
        </div>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true" ></span>
        <span class="visually-hidden">Previous</span>
      </button>

      <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>

           <div id="wide-buttons" style="margin-top: 10px; margin-left: -4.5px; margin-bottom: 50px;">
        <% if current_user && current_user == @product.business.owner %>
          <div class="d-flex aligin-items-center flex-wrap">
            <div class="m-2">
              <%= link_to "Go back to products!", business_products_path(@product.business), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Edit this product!", edit_business_product_path(@product.business, @product), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Delete", business_product_path(@product.business, @product), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "blue-btn",  style: "background-color:red !important;"%>
            </div>
             <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>

        <% elsif current_user %>
          <div class="d-flex align-items-center flex-wrap">
            <div class="m-2">
              <%= link_to "Add to my itinerary + ", create_itinerary_path(@product, itinerary: {name: "My itinerary #{current_user.saved_itineraries.all.count + 1}", status: false}), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "See the business", business_path(@product.business), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "More from this seller", business_products_path(@product.business), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>
        <% else %>
            <div class="m-2">
              <%= link_to "Login to add this item to your itinerary", new_user_registration_path, class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>

  <div id=info-container-picture-business-product-show class="d-flex justify-content-center pt-3" style= "width: 100vw; background-color: white">
    <div class="" style=" width: 95vw; ">
      <div class="m-2" style="bottom: 0; right: 0">
        <div class="mt-1">
          <h2 style="font-weight: bold"><%=@product.name%></h2>
          <p style="font-weight: bold"><i class="fa-solid fa-shop"></i> Sold by: <%=@product.business.name%></p>
          <hr>
          <h2 style="margin-left: 5px; margin-top: 5px;" ><i class="fa-solid fa-tag"></i> Price: £<%= "%.2f" % @product.price.round%></h2>
          <p><i class="fa-solid fa-star"></i> Brand: <%= @product.brand%></p>
          <p><i class="fa-solid fa-circle-question"></i> Category :<%= @product.category %></p>
          <p><i class="fa-solid fa-clock"></i> <%= @product.business.opening_time.strftime("%H:%M")%> - <%= @product.business.closing_time.strftime("%H:%M")%><p>
        </div>
      </div>
      <div class="m-2">
        <h2>Product info</h2>
        <p><i class="fa-solid fa-list"></i> <%=@product.description%></p>
      </div>
      <div id="narrow-buttons">
        <% if current_user && current_user == @product.business.owner %>
          <div class="d-flex align-items-center flex-wrap">
            <div class="m-2">
              <%= link_to "Go back to products!", business_products_path(@product.business), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Edit this product!", edit_business_product_path(@product.business, @product), class: "blue-btn"%>
            </div>
            <div class="m-2">
              <%= link_to "Delete", business_product_path(@product.business, @product), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"},  class: "blue-btn", style: "background-color:red !important;" %>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>
        <% elsif current_user%>
          <div class="d-flex align-items-center flex-wrap">
            <div class="m-2">
              <%= link_to "Add to my itinerary + ", create_itinerary_path(@product, itinerary: {name: "My itinerary #{current_user.saved_itineraries.all.count + 1}", status: false}), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "See the business", business_path(@product.business), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "More from this seller", business_products_path(@product.business), class: "blue-btn" %>
            </div>
            <div class="m-2">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
          </div>
        <% else %>
          <div class="m-3">
            <%= link_to "Login to add this item to your itinerary", new_user_registration_path, class: "blue-btn"%>
          </div>
          <div class="m-3">
              <%= link_to "Back", :back, class: "blue-btn" %>
            </div>
        <% end %>
        <hr>
        </div>
         <div id="show-map" class="map" style="width: 100%; height: 30vh; border-radius-button: 10px; margin-bottom: 5vh;"
          data-controller="map-show"
          data-map-show-markers-value="<%= @markers.to_json %>"
          data-map-show-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>
  </div>

</div>